export type DyddCourseUnitType =
  | "orientation"
  | "normal"
  | "assessment-link"
  | "designid-reflection"
  | "workbook-checkpoint"
  | "pathfinder"
  | "completion";
export type DyddCourseUnit = {
  row: number;
  slug: string;
  type: DyddCourseUnitType;
  typeLabel: string;
  section: string;
  title: string;
  duration: string;
  bookPages?: string;
  workbookSection?: string;
  workbookPages?: string;
  notes?: string;
  lessonMainIdea: string;
  anchorScripture?: string;
  focus?: string[];
  media?: {
    image?: string;
    label: string;
    type: "image" | "video";
  };
  practice?: {
    prompt: string;
    title: string;
  };
  reflectionPrompt: string;
  teachingBlocks: string[];
};
export type DyddCourseModule = {
  slug: string;
  title: string;
  kicker: string;
  summary: string;
  units: DyddCourseUnit[];
};
export const dyddMainCourseOutline: DyddCourseModule[] = [
  {
    slug: "welcome-and-orientation",
    title: "Welcome & Orientation",
    kicker: "1: Welcome & Orientation",
    summary: "Open the trail, explain how the digital class works, and help the learner choose a pace.",
    units: [
      {
        row: 2,
        slug: "welcome-and-orientation-welcome-to-discover-your-divine-design-2",
        type: "orientation",
        section: "Welcome & Orientation",
        title: "Welcome to Discover Your Divine Design",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into Welcome to Discover Your Divine Design and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after Welcome to Discover Your Divine Design?",
        teachingBlocks: [
          "This lesson introduces Welcome to Discover Your Divine Design as part of the Welcome & Orientation movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 3,
        slug: "welcome-and-orientation-course-outline-and-objectives-3",
        type: "orientation",
        section: "Welcome & Orientation",
        title: "Course Outline & Objectives",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into Course Outline & Objectives and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after Course Outline & Objectives?",
        teachingBlocks: [
          "This lesson introduces Course Outline & Objectives as part of the Welcome & Orientation movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 4,
        slug: "welcome-and-orientation-how-this-journey-works-4",
        type: "orientation",
        section: "Welcome & Orientation",
        title: "How This Journey Works",
        typeLabel: "Orientation",
        duration: "6-8 min",
        lessonMainIdea: "A video-led orientation lesson that gives John a clean space to explain the rhythm of each chapter before the learner reaches CARE prompts.",
        focus: [
          "Introduce the recurring chapter flow: teaching, reflection, CARE, and Pathfinder.",
          "Explain that assessments are mirrors that help personalize the journey.",
          "Clarify what stays private and what can later be shared in a Camp Circle.",
        ],
        media: {
          image: "/brand/john-author-cartoon-dydd-style.png",
          label: "Video teaching space with John",
          type: "video",
        },
        practice: {
          title: "Pace decision",
          prompt: "Choose whether you are walking this weekly, in a short intensive, with a partner, or inside a group. That pace will shape reminders and chapter expectations later.",
        },
        reflectionPrompt: "What rhythm will help you walk this journey with steadiness instead of rushing it?",
        teachingBlocks: [
          "Every chapter should feel familiar without becoming flat. The learner begins with a short teaching section, moves into reflection, practices the CARE rhythm, and carries Pathfinder language forward when a chapter is building toward niche.",
          "The goal is not to finish a checklist. The goal is to slow down enough to recognize what God is revealing and then take the next faithful step with it.",
          "DesignID, Spiritual Gifts, DesignPD, and FruitLife 360 can eventually sit beside the lesson and speak directly into the learner's path. The course still needs one clear path for everyone, but the app can place personal insight beside that path when the learner is signed in and records are connected.",
          "Journal entries, CARE reflections, and assessment records belong first to the learner. Camp Circle tools can invite shared progress, reminders, and discussion, while private workbook answers stay protected.",
        ],
      },
      {
        row: 5,
        slug: "welcome-and-orientation-course-resources-5",
        type: "orientation",
        section: "Welcome & Orientation",
        title: "Course Resources",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into Course Resources and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after Course Resources?",
        teachingBlocks: [
          "This lesson introduces Course Resources as part of the Welcome & Orientation movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
    ],
  },
  {
    slug: "what-is-dydd",
    title: "What is DYDD?",
    kicker: "2: What is DYDD?",
    summary: "Frame grace, purpose, DESIGN, CARE, assessments, and Pathfinder before the chapter work begins.",
    units: [
      {
        row: 6,
        slug: "what-is-dydd-what-is-dydd-6",
        type: "orientation",
        section: "What is DYDD?",
        title: "What is DYDD?",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into What is DYDD? and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after What is DYDD?",
        teachingBlocks: [
          "This lesson introduces What is DYDD? as part of the What is DYDD? movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 7,
        slug: "what-is-dydd-grace-7",
        type: "orientation",
        section: "What is DYDD?",
        title: "Grace",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into Grace and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after Grace?",
        teachingBlocks: [
          "This lesson introduces Grace as part of the What is DYDD? movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 8,
        slug: "what-is-dydd-on-purpose-for-purpose-8",
        type: "orientation",
        section: "What is DYDD?",
        title: "On Purpose For Purpose",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into On Purpose For Purpose and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after On Purpose For Purpose?",
        teachingBlocks: [
          "This lesson introduces On Purpose For Purpose as part of the What is DYDD? movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 9,
        slug: "what-is-dydd-d-e-s-i-g-n-9",
        type: "orientation",
        section: "What is DYDD?",
        title: "D.E.S.I.G.N",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into D.E.S.I.G.N and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after D.E.S.I.G.N?",
        teachingBlocks: [
          "This lesson introduces D.E.S.I.G.N as part of the What is DYDD? movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 10,
        slug: "what-is-dydd-how-to-c-a-r-e-10",
        type: "normal",
        section: "What is DYDD?",
        title: "How to C.A.R.E",
        bookPages: "p8 - p9",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach How to C.A.R.E with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        reflectionPrompt: "What do you need to notice or practice after How to C.A.R.E?",
        teachingBlocks: [
          "This lesson introduces How to C.A.R.E as part of the What is DYDD? movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 11,
        slug: "what-is-dydd-dydd-assessments-11",
        type: "assessment-link",
        section: "What is DYDD?",
        title: "DYDD Assessments",
        typeLabel: "Assessment step",
        duration: "8-12 min",
        lessonMainIdea: "Help the learner complete or reconnect the assessment, then bring the result back into the Journey record.",
        reflectionPrompt: "What did this assessment help you see, confirm, or question?",
        teachingBlocks: [
          "This lesson should briefly explain why the assessment matters, send the learner to complete or review it, and then confirm whether the result is connected to their account.",
          "The deeper teaching can stay in the assessment course. The Journey only needs the bridge, the reflection, and the return path.",
        ],
      },
      {
        row: 12,
        slug: "what-is-dydd-pathfinder-niche-12",
        type: "orientation",
        section: "What is DYDD?",
        title: "Pathfinder (Niche)",
        typeLabel: "Orientation",
        duration: "4-6 min",
        lessonMainIdea: "Welcome the learner into Pathfinder (Niche) and make the next part of the journey feel clear, doable, and personal.",
        reflectionPrompt: "What do you need to notice or practice after Pathfinder (Niche)?",
        teachingBlocks: [
          "This lesson introduces Pathfinder (Niche) as part of the What is DYDD? movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
    ],
  },
  {
    slug: "identity",
    title: "Identity",
    kicker: "Chapter 1: Identity",
    summary: "Begin with whose you are before what you do, then use DesignID as a helpful mirror.",
    units: [
      {
        row: 14,
        slug: "identity-purpose-14",
        type: "normal",
        section: "Identity Overview",
        title: "Purpose",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Purpose with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "What do you need to notice or practice after Purpose?",
        teachingBlocks: [
          "This lesson introduces Purpose as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 15,
        slug: "identity-handiwork-15",
        type: "normal",
        section: "Identity Overview",
        title: "Handiwork",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Handiwork with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "What do you need to notice or practice after Handiwork?",
        teachingBlocks: [
          "This lesson introduces Handiwork as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 16,
        slug: "identity-who-vs-whose-16",
        type: "normal",
        section: "Identity Overview",
        title: "Who Vs. Whose",
        bookPages: "p12 - p17",
        workbookSection: "Who are you and whose are you?",
        workbookPages: "p7 - p8",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Who Vs. Whose with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "Who are you and whose are you?",
        teachingBlocks: [
          "This lesson introduces Who Vs. Whose as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 17,
        slug: "identity-good-works-17",
        type: "normal",
        section: "Identity Overview",
        title: "Good Works",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Good Works with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "What do you need to notice or practice after Good Works?",
        teachingBlocks: [
          "This lesson introduces Good Works as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 18,
        slug: "identity-niche-18",
        type: "normal",
        section: "Identity Overview",
        title: "Niche",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Niche with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "What do you need to notice or practice after Niche?",
        teachingBlocks: [
          "This lesson introduces Niche as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 19,
        slug: "identity-the-designid-lens-what-is-in-the-report-19",
        type: "designid-reflection",
        section: "Identity Assessment",
        title: "The DesignID Lens: What is in the report?",
        bookPages: "p18 - p20",
        workbookSection: "Unpack your reflections",
        workbookPages: "p9 - p18",
        notes: "Refer them to D-ID course access for deeper dive",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Identity, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "Unpack your reflections",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Identity, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 20,
        slug: "identity-identity-among-believers-20",
        type: "normal",
        section: "Identity Assessment",
        title: "Identity among believers",
        bookPages: "p21 - p27",
        workbookSection: "Your Identity Among Believers",
        workbookPages: "p19 - p21",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Identity among believers with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "Your Identity Among Believers",
        teachingBlocks: [
          "This lesson introduces Identity among believers as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 21,
        slug: "identity-the-design-reflections-and-love-21",
        type: "designid-reflection",
        section: "Identity Assessment",
        title: "The Design Reflections and Love",
        workbookSection: "The Design Reflections and Love",
        workbookPages: "p22 - p24",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Identity, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "The Design Reflections and Love",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Identity, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 22,
        slug: "identity-love-your-neighbor-as-yourself-22",
        type: "normal",
        section: "Identity Assessment",
        title: "Love your neighbor as yourself",
        bookPages: "p28 - p37",
        workbookSection: "Love Yourself, Love Others",
        workbookPages: "p25 - p26",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Love your neighbor as yourself with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "Love Yourself, Love Others",
        teachingBlocks: [
          "This lesson introduces Love your neighbor as yourself as part of the Identity movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 23,
        slug: "identity-reflections-and-one-anothering-23",
        type: "designid-reflection",
        section: "Identity Assessment",
        title: "Reflections and One Anothering",
        workbookSection: "Reflections and One Anothering",
        workbookPages: "p27 - p30",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Identity, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "Reflections and One Anothering",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Identity, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 24,
        slug: "identity-niche-preparation-identity-24",
        type: "pathfinder",
        section: "Identity Pathfinder: Niche",
        title: "Niche Preparation: Identity",
        bookPages: "p38 - p40",
        workbookSection: "I believe God created me...",
        workbookPages: "p31 - p32",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Identity chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Ephesians 2:10",
        reflectionPrompt: "I believe God created me...",
        teachingBlocks: [
          "This Pathfinder moment turns the Identity chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
    ],
  },
  {
    slug: "expertise",
    title: "Expertise",
    kicker: "Chapter Two: Expertise",
    summary: "Name talents, competencies, and hard-won wisdom as faithful stewardship.",
    units: [
      {
        row: 26,
        slug: "expertise-the-journey-to-expertise-26",
        type: "normal",
        section: "Expertise Journey",
        title: "The Journey to Expertise",
        bookPages: "p41 - p46",
        workbookSection: "The slow and faithful journey to Expertise",
        workbookPages: "p34 - p36",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach The Journey to Expertise with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "The slow and faithful journey to Expertise",
        teachingBlocks: [
          "This lesson introduces The Journey to Expertise as part of the Expertise movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 27,
        slug: "expertise-talent-27",
        type: "normal",
        section: "Expertise Journey",
        title: "Talent",
        bookPages: "p46 - p47",
        workbookSection: "What are your talents?",
        workbookPages: "p37",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Talent with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "What are your talents?",
        teachingBlocks: [
          "This lesson introduces Talent as part of the Expertise movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 28,
        slug: "expertise-competence-28",
        type: "normal",
        section: "Expertise Journey",
        title: "Competence",
        bookPages: "p48 - p50",
        workbookSection: "Where are you growing in Competency?",
        workbookPages: "p38 - p39",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Competence with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "Where are you growing in Competency?",
        teachingBlocks: [
          "This lesson introduces Competence as part of the Expertise movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 29,
        slug: "expertise-expertise-29",
        type: "normal",
        section: "Expertise Journey",
        title: "Expertise",
        bookPages: "p51 - p60",
        workbookSection: "What is expertise?",
        workbookPages: "p40 - p41",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Expertise with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "What is expertise?",
        teachingBlocks: [
          "This lesson introduces Expertise as part of the Expertise movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 30,
        slug: "expertise-being-vs-doing-30",
        type: "normal",
        section: "Deep Efforts produce deep results",
        title: "Being Vs. Doing",
        bookPages: "p61 - p66",
        workbookSection: "Being Before Doing",
        workbookPages: "p42 - p44",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Being Vs. Doing with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "Being Before Doing",
        teachingBlocks: [
          "This lesson introduces Being Vs. Doing as part of the Expertise movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 31,
        slug: "expertise-applied-capacity-31",
        type: "normal",
        section: "Deep Efforts produce deep results",
        title: "Applied Capacity",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Applied Capacity with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "What do you need to notice or practice after Applied Capacity?",
        teachingBlocks: [
          "This lesson introduces Applied Capacity as part of the Expertise movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 32,
        slug: "expertise-connecting-identity-and-expertise-32",
        type: "designid-reflection",
        section: "Deep Efforts produce deep results",
        title: "Connecting Identity & Expertise",
        bookPages: "p67",
        workbookSection: "The Reflections: Talent - Competency - Expertise",
        workbookPages: "p45 - p46",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Expertise, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "The Reflections: Talent - Competency - Expertise",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Expertise, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 33,
        slug: "expertise-niche-preparation-expertise-33",
        type: "pathfinder",
        section: "Expertise Pathfinder: Niche",
        title: "Niche Preparation: Expertise",
        bookPages: "p68 - p69",
        workbookSection: "Which will enable me to use my...",
        workbookPages: "p47 - p48",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Expertise chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Colossians 3:23",
        reflectionPrompt: "Which will enable me to use my...",
        teachingBlocks: [
          "This Pathfinder moment turns the Expertise chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
    ],
  },
  {
    slug: "story",
    title: "Story",
    kicker: "Chapter 3: Story",
    summary: "Gather formative stories with care so pain, testimony, culture, work, and church become part of discernment.",
    units: [
      {
        row: 35,
        slug: "story-why-story-matters-35",
        type: "normal",
        section: "Your Story Matters",
        title: "Why story matters",
        bookPages: "p70 - p73",
        workbookSection: "The moments that shape us",
        workbookPages: "p50",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Why story matters with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "The moments that shape us",
        teachingBlocks: [
          "This lesson introduces Why story matters as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 36,
        slug: "story-god-never-wastes-a-hurt-36",
        type: "normal",
        section: "Your Story Matters",
        title: "God never wastes a hurt",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach God never wastes a hurt with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "What do you need to notice or practice after God never wastes a hurt?",
        teachingBlocks: [
          "This lesson introduces God never wastes a hurt as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 37,
        slug: "story-what-is-a-testimony-37",
        type: "normal",
        section: "Testimony",
        title: "What is a testimony?",
        bookPages: "p74 - p76",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach What is a testimony? with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "What do you need to notice or practice after What is a testimony??",
        teachingBlocks: [
          "This lesson introduces What is a testimony? as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 38,
        slug: "story-pauls-testimony-38",
        type: "normal",
        section: "Testimony",
        title: "Paul's Testimony",
        bookPages: "p76 - p81",
        workbookSection: "Sharing your faith story",
        workbookPages: "p51 - p52",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Paul's Testimony with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "Sharing your faith story",
        teachingBlocks: [
          "This lesson introduces Paul's Testimony as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 39,
        slug: "story-family-and-culture-39",
        type: "normal",
        section: "Your Stories",
        title: "Family & Culture",
        bookPages: "p82 - p88",
        workbookSection: "Your Family & Culture story",
        workbookPages: "p53 - p55",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Family & Culture with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "Your Family & Culture story",
        teachingBlocks: [
          "This lesson introduces Family & Culture as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 40,
        slug: "story-your-work-matters-40",
        type: "normal",
        section: "Your Stories",
        title: "Your Work Matters!",
        bookPages: "p89 - p92",
        workbookSection: "Called where you are",
        workbookPages: "p56 - p58",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Your Work Matters! with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "Called where you are",
        teachingBlocks: [
          "This lesson introduces Your Work Matters! as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 41,
        slug: "story-your-church-story-41",
        type: "normal",
        section: "Your Stories",
        title: "Your Church Story",
        bookPages: "p94 - p94",
        workbookSection: "Church Vs. The Body of Christ",
        workbookPages: "p58 - p60",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Your Church Story with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "Church Vs. The Body of Christ",
        teachingBlocks: [
          "This lesson introduces Your Church Story as part of the Story movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 42,
        slug: "story-divine-reflections-within-your-stories-42",
        type: "designid-reflection",
        section: "Your Stories",
        title: "Divine reflections within your stories",
        workbookSection: "Divine reflections within your stories",
        workbookPages: "p61 - p62",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Story, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "Divine reflections within your stories",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Story, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 43,
        slug: "story-what-is-learned-helplessness-43",
        type: "designid-reflection",
        section: "Learned Helplessness",
        title: "What is Learned Helplessness?",
        notes: "This will need a \"new workbook\" like experience created\"",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Story, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "What do you need to notice or practice after What is Learned Helplessness??",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Story, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 44,
        slug: "story-shadows-anxiety-and-fear-44",
        type: "designid-reflection",
        section: "Learned Helplessness",
        title: "Shadows: Anxiety & Fear",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Story, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "What do you need to notice or practice after Shadows: Anxiety & Fear?",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Story, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 45,
        slug: "story-from-fear-to-alignment-45",
        type: "designid-reflection",
        section: "Learned Helplessness",
        title: "From fear to alignment",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Story, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "What do you need to notice or practice after From fear to alignment?",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Story, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 46,
        slug: "story-niche-preparation-story-46",
        type: "pathfinder",
        section: "Story Pathfinder: Niche",
        title: "Niche Preparation: Story",
        bookPages: "p95 - p96",
        workbookSection: "Coming From...",
        workbookPages: "p63 - p64",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Story chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Romans 8:28",
        reflectionPrompt: "Coming From...",
        teachingBlocks: [
          "This Pathfinder moment turns the Story chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
    ],
  },
  {
    slug: "desire",
    title: "Desire",
    kicker: "Chapter 4: Desire",
    summary: "Discern the desires of the heart and test them against identity, expertise, and story.",
    units: [
      {
        row: 48,
        slug: "desire-desire-why-you-say-think-live-and-love-the-way-you-do-48",
        type: "designid-reflection",
        section: "What lights your fire?",
        title: "Desire: Why you say, think, live, & love the way you do.",
        bookPages: "p97 - p105",
        workbookSection: "The reflections and the desires of the heart",
        workbookPages: "p65 - p69",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Desire, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "The reflections and the desires of the heart",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Desire, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 49,
        slug: "desire-aligning-desire-with-purpose-49",
        type: "normal",
        section: "What lights your fire?",
        title: "Aligning Desire with Purpose",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Aligning Desire with Purpose with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "What do you need to notice or practice after Aligning Desire with Purpose?",
        teachingBlocks: [
          "This lesson introduces Aligning Desire with Purpose as part of the Desire movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 50,
        slug: "desire-will-vs-ways-50",
        type: "normal",
        section: "What lights your fire?",
        title: "Will Vs. Ways",
        bookPages: "p106 - p108",
        workbookSection: "Desire aligned with God's Design",
        workbookPages: "p70 - p71",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Will Vs. Ways with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "Desire aligned with God's Design",
        teachingBlocks: [
          "This lesson introduces Will Vs. Ways as part of the Desire movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 51,
        slug: "desire-identity-and-desire-51",
        type: "normal",
        section: "Pulling it all together",
        title: "Identity & Desire",
        bookPages: "p109",
        workbookSection: "Pulling it all together",
        workbookPages: "p72 - p74",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Identity & Desire with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "Pulling it all together",
        teachingBlocks: [
          "This lesson introduces Identity & Desire as part of the Desire movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 52,
        slug: "desire-expertise-and-desire-52",
        type: "normal",
        section: "Pulling it all together",
        title: "Expertise & Desire",
        bookPages: "p110 - p112",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Expertise & Desire with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "What do you need to notice or practice after Expertise & Desire?",
        teachingBlocks: [
          "This lesson introduces Expertise & Desire as part of the Desire movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 53,
        slug: "desire-story-and-desire-53",
        type: "normal",
        section: "Pulling it all together",
        title: "Story & Desire",
        bookPages: "p112 - p116",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Story & Desire with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "What do you need to notice or practice after Story & Desire?",
        teachingBlocks: [
          "This lesson introduces Story & Desire as part of the Desire movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 54,
        slug: "desire-precious-vs-worthless-54",
        type: "normal",
        section: "Pulling it all together",
        title: "Precious vs. Worthless",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Precious vs. Worthless with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "What do you need to notice or practice after Precious vs. Worthless?",
        teachingBlocks: [
          "This lesson introduces Precious vs. Worthless as part of the Desire movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 55,
        slug: "desire-niche-preparation-desire-55",
        type: "pathfinder",
        section: "Desire Pathfinder: Niche",
        title: "Niche Preparation: Desire",
        bookPages: "p117",
        workbookSection: "Impassioned by...",
        workbookPages: "p75",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Desire chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Psalm 37:4",
        reflectionPrompt: "Impassioned by...",
        teachingBlocks: [
          "This Pathfinder moment turns the Desire chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
    ],
  },
  {
    slug: "gifts",
    title: "Gifts",
    kicker: "Chapter 5: Gifts",
    summary: "Place spiritual gifts inside the whole design, moving from preparation to Spirit-empowered service.",
    units: [
      {
        row: 57,
        slug: "gifts-the-spiritual-gifts-assessment-with-dydd-57",
        type: "normal",
        section: "From Preparation to Power",
        title: "The spiritual Gifts Assessment with DYDD",
        notes: "Link to assessment and course upon completion",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach The spiritual Gifts Assessment with DYDD with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "What do you need to notice or practice after The spiritual Gifts Assessment with DYDD?",
        teachingBlocks: [
          "This lesson introduces The spiritual Gifts Assessment with DYDD as part of the Gifts movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 58,
        slug: "gifts-what-are-and-are-not-the-spiritual-gifts-58",
        type: "normal",
        section: "From Preparation to Power",
        title: "What are and are not the Spiritual Gifts?",
        bookPages: "p119 - p128",
        workbookSection: "From Design to Power",
        workbookPages: "p76 - p79",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach What are and are not the Spiritual Gifts? with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "From Design to Power",
        teachingBlocks: [
          "This lesson introduces What are and are not the Spiritual Gifts? as part of the Gifts movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 59,
        slug: "gifts-unpack-your-spiritual-gifts-59",
        type: "workbook-checkpoint",
        section: "From Preparation to Power",
        title: "Unpack Your Spiritual Gifts",
        workbookSection: "Unpack Your Spiritual Gifts",
        workbookPages: "p80 - p81",
        typeLabel: "Workbook checkpoint",
        duration: "8-12 min",
        lessonMainIdea: "Slow down and complete the workbook reflection: Unpack Your Spiritual Gifts.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "Unpack Your Spiritual Gifts",
        teachingBlocks: [
          "This checkpoint should feel like guided reflection, not a plain form. It gives the learner space to answer the workbook and save the entry as part of the personal record.",
          "Later, these saved responses can shape progress tracking, companion prompts, and Camp Circle visibility without exposing private content.",
        ],
      },
      {
        row: 60,
        slug: "gifts-spiritual-gifts-and-identity-60",
        type: "designid-reflection",
        section: "Gifts in Design",
        title: "Spiritual Gifts & Identity",
        bookPages: "p129",
        workbookSection: "Spiritual Gifts and your divine reflection",
        workbookPages: "p82 - p84",
        typeLabel: "DesignID reflection",
        duration: "10-15 min",
        lessonMainIdea: "Use DesignID as a mirror inside Gifts, helping the learner connect assessment language to faithful love and service.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "Spiritual Gifts and your divine reflection",
        teachingBlocks: [
          "DesignID should function here as a mirror, not a box. The learner can notice how their reflection pattern shapes love, learning, contribution, capacity, and pressure responses.",
          "Placed inside Gifts, this reflection keeps the assessment connected to the Journey instead of sending the learner into a disconnected side course.",
        ],
      },
      {
        row: 61,
        slug: "gifts-spiritual-gifts-and-expertise-61",
        type: "normal",
        section: "Gifts in Design",
        title: "Spiritual Gifts & Expertise",
        bookPages: "p130 - p131",
        workbookSection: "Considering your path forward",
        workbookPages: "p85 - p86",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Spiritual Gifts & Expertise with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "Considering your path forward",
        teachingBlocks: [
          "This lesson introduces Spiritual Gifts & Expertise as part of the Gifts movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 62,
        slug: "gifts-spiritual-gifts-and-story-desire-62",
        type: "normal",
        section: "Gifts in Design",
        title: "Spiritual gifts & Story/Desire",
        bookPages: "p132 - 135",
        workbookSection: "Spiritual Gifts: Pulling it all together",
        workbookPages: "p87 - p88",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Spiritual gifts & Story/Desire with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "Spiritual Gifts: Pulling it all together",
        teachingBlocks: [
          "This lesson introduces Spiritual gifts & Story/Desire as part of the Gifts movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 63,
        slug: "gifts-niche-preparation-gifts-63",
        type: "pathfinder",
        section: "Gifts Pathfinder: Niche",
        title: "Niche Preparation: Gifts",
        bookPages: "p136",
        workbookSection: "Supported by...",
        workbookPages: "p89",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Gifts chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "1 Peter 4:10",
        reflectionPrompt: "Supported by...",
        teachingBlocks: [
          "This Pathfinder moment turns the Gifts chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
    ],
  },
  {
    slug: "niche",
    title: "Niche",
    kicker: "Chapter 6: Niche",
    summary: "Bring the whole journey together into a clear, faithful niche declaration.",
    units: [
      {
        row: 65,
        slug: "niche-who-do-you-see-65",
        type: "normal",
        section: "Called to Purpose",
        title: "Who do you see?",
        notes: "Matt 5: 3-10. blessed for...",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Who do you see? with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "What do you need to notice or practice after Who do you see??",
        teachingBlocks: [
          "This lesson introduces Who do you see? as part of the Niche movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 66,
        slug: "niche-who-is-calling-66",
        type: "normal",
        section: "Called to Purpose",
        title: "Who is calling?",
        notes: "General vs. specific, what if you don't know. Purpose - Action - Fruition",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach Who is calling? with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "What do you need to notice or practice after Who is calling??",
        teachingBlocks: [
          "This lesson introduces Who is calling? as part of the Niche movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 67,
        slug: "niche-the-promised-land-journey-67",
        type: "normal",
        section: "Called to Purpose",
        title: "The Promised Land Journey",
        typeLabel: "Teaching lesson",
        duration: "6-9 min",
        lessonMainIdea: "Teach The Promised Land Journey with enough clarity and warmth that the learner is ready to answer the attached workbook section.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "What do you need to notice or practice after The Promised Land Journey?",
        teachingBlocks: [
          "This lesson introduces The Promised Land Journey as part of the Niche movement of Discover Your Divine Design. It should give enough teaching to make the next reflection meaningful without overwhelming the learner.",
          "The rhythm is steady: teach the idea, name what to notice, invite a small act of reflection, then attach the relevant workbook section at the bottom so progress is captured in one place.",
        ],
      },
      {
        row: 68,
        slug: "niche-pathfinder-preparing-your-niche-declaration-68",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Pathfinder: Preparing your niche declaration",
        bookPages: "p137 - p143",
        workbookSection: "I believe God created me...",
        workbookPages: "p90 - p94",
        notes: "Full Pathfinder Niche builder here. Able to pull from their assessments, all entries, and collaboate with Dydi (Agent)",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "I believe God created me...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 69,
        slug: "niche-coming-from-69",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Coming from...",
        workbookSection: "Coming from...",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "Coming from...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 70,
        slug: "niche-which-will-enable-me-to-use-my-70",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Which will enable me to use my...",
        workbookSection: "Which will enable me to use my...",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "Which will enable me to use my...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 71,
        slug: "niche-impassioned-by-71",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Impassioned by...",
        workbookSection: "Impassioned by...",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "Impassioned by...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 72,
        slug: "niche-supported-by-72",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Supported by...",
        workbookSection: "Supported by...",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "Supported by...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 73,
        slug: "niche-resulting-in-my-73",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Resulting in my...",
        workbookSection: "Resulting in my...",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "Resulting in my...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 74,
        slug: "niche-encouraged-by-74",
        type: "pathfinder",
        section: "Step in to your purpose",
        title: "Encouraged by...",
        workbookSection: "Encouraged by...",
        typeLabel: "Pathfinder / niche",
        duration: "12-20 min",
        lessonMainIdea: "Shape the Niche chapter into one useful line for the learner's developing niche declaration.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "Encouraged by...",
        teachingBlocks: [
          "This Pathfinder moment turns the Niche chapter into language the learner can carry forward. The goal is not perfection; the goal is a faithful draft that captures what is becoming clear.",
          "The mature version of this lesson should review saved reflections, surface repeated words, invite companion guidance, and preserve a draft line for the final niche declaration.",
        ],
      },
      {
        row: 75,
        slug: "niche-congratulations-75",
        type: "completion",
        section: "Congratulations",
        title: "Congratulations",
        typeLabel: "Completion",
        duration: "5-8 min",
        lessonMainIdea: "Close the Journey with prayer, celebration, and one concrete next step beyond the course.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "What next faithful step are you ready to take?",
        teachingBlocks: [
          "The ending should feel like a commissioning, not a hard stop. The learner has gathered language, evidence, prayers, and next steps that now need to be lived.",
          "This unit can point them toward their next faithful experiment, future coaching, a Camp Circle, or deeper work with the Field Guide.",
        ],
      },
      {
        row: 76,
        slug: "niche-prayer-76",
        type: "completion",
        section: "Congratulations",
        title: "Prayer",
        typeLabel: "Completion",
        duration: "5-8 min",
        lessonMainIdea: "Close the Journey with prayer, celebration, and one concrete next step beyond the course.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "What next faithful step are you ready to take?",
        teachingBlocks: [
          "The ending should feel like a commissioning, not a hard stop. The learner has gathered language, evidence, prayers, and next steps that now need to be lived.",
          "This unit can point them toward their next faithful experiment, future coaching, a Camp Circle, or deeper work with the Field Guide.",
        ],
      },
      {
        row: 77,
        slug: "niche-whats-next-77",
        type: "completion",
        section: "Congratulations",
        title: "What's next",
        typeLabel: "Completion",
        duration: "5-8 min",
        lessonMainIdea: "Close the Journey with prayer, celebration, and one concrete next step beyond the course.",
        anchorScripture: "Matthew 5:16",
        reflectionPrompt: "What next faithful step are you ready to take?",
        teachingBlocks: [
          "The ending should feel like a commissioning, not a hard stop. The learner has gathered language, evidence, prayers, and next steps that now need to be lived.",
          "This unit can point them toward their next faithful experiment, future coaching, a Camp Circle, or deeper work with the Field Guide.",
        ],
      },
    ],
  },
];

export const dyddMainCourseStats = {
  moduleCount: dyddMainCourseOutline.length,
  unitCount: dyddMainCourseOutline.reduce((count, module) => count + module.units.length, 0),
  pathfinderCount: dyddMainCourseOutline.reduce((count, module) => count + module.units.filter((unit) => unit.type === "pathfinder").length, 0),
  designIdReflectionCount: dyddMainCourseOutline.reduce((count, module) => count + module.units.filter((unit) => unit.type === "designid-reflection").length, 0),
};
